[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[dependencies]
# C++ dependencies
cxx-compiler = ">=1.11.0,<2"
cmake = ">=4.1.1,<5"
libboost-devel = ">=1.89.0,<2"

# Python dependency
python = ">=3.13.7,<3.14"

[tasks]
# C++ tasks
configure = "cmake -B build -DCMAKE_BUILD_TYPE=Release"
build = { cmd = "cmake --build build --config Release", depends-on = ["configure"]}
test = { cmd = "ctest --test-dir build -C Release", depends-on = ["build"] }

# Python task
this = "python -c 'import this'"
