[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[dependencies]
# C++ dependencies
cxx-compiler = ">=1.11.0,<2"
boost-cpp = ">=1.85.0,<2"
cmake = ">=4.1.1,<5"

# Python dependency
python = ">=3.13.7,<3.14"

[tasks]
configure = "cmake -B build"
build = { cmd = "cmake --build build", depends-on = ["configure"]}
test = { cmd = "build/cppcon", depends-on = ["build"] }

py-test = 'python -c "import subprocess; subprocess.run([\"build/cppcon\"])"'
