[workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
cpp-package = { path = "src/cpp-package" }
python-package = { path = "src/python-package" }

[tasks]
cpp = "cppcon"
py = "python-script"