[package] 
name = "cpp-package"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-cmake"
version = "0.3.*"


[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"] 

[package.host-dependencies]
boost-cpp = ">=1.85.0,<2"
