[package] 
name = "cpp-package"
version = "0.1.1"

[package.build.backend]
name = "pixi-build-cmake"
version = "0.3.*"
channels = ["https://prefix.dev/pixi-build-backends", "https://prefix.dev/conda-forge"]

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"] 

[package.host-dependencies]
boost-cpp = ">=1.85.0,<2"
