name: CI without Pixi
on:
  push:
  pull_request:

jobs:
  test:
    name: No-Pixi on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # ---------- deps ----------
      - name: Install deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev

      - name: Install deps (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install boost

      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install boost-msvc-14.3 --no-progress -y

      # ---------- configure ----------
      - name: Configure (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Configure (Windows, MSVC)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $cmakeArgs = @(
            "-S", ".", "-B", "build",
            "-G", "Visual Studio 17 2022"
          )
          cmake @cmakeArgs

      # ---------- build ----------
      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake --build build --config Release

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build build --config Release

      # ---------- test ----------
      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure

      # ---------- python ----------
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - run: python -c "import this"